---
driver:
  name: vagrant
  vm_hostname: myagent
  customize:
    memory: 1024
    cpus: 1
    name: myagent
  network:
    - ["public_network", bridge: '<%= ENV['ETH'] %>']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec

platforms:
  - name: mycsc-7.4

suites:
  - name: myagent
    run_list:
#      - recipe[apm_agent::install_agent]
#      - recipe[apm_agent::install_decoder]
#      - recipe[apm_agent::get_token]
      - recipe[apm_agent::get_threshold]
#      - recipe[apm_agent::create_threshold]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
